version: '3.4'

services:


  #rabbitmq:
  #  image: rabbitmq
  #  command: rabbitmq-server
  #  hostname: local-rabbitmq
  #  ports:
  #      - 5672:5672
  #      - 15672:15672
  #  environment:
  #    RABBITMQ_DEFAULT_USER: "guest"
  #    RABBITMQ_DEFAULT_PASS: "guest"
  #  #expose:
  #  #  - 5672
  #  #  - 15672
  #  healthcheck:
  #    test: [ "CMD", "nc", "-z", "localhost", "5672" ]
  #    interval: 5s
  #    timeout: 15s
  #    retries: 1

  #rabitmq
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: local-rabbitmq
    #networks:
    #    - my-network
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

      # database
  db:
    restart: always
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - 1433:1433
      # botserver
  botserver:
    image: ${DOCKER_REGISTRY-}botserver
    restart: always
    build:
      context: .
      dockerfile: BotServer/Dockerfile
    depends_on:
      - db
      - rabbitmq

      # serverapp
  serverapp:
    image: ${DOCKER_REGISTRY-}vkserviceapplication
    restart: always
    build:
      context: .
      dockerfile: VkServiceApplication/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - my-network

      #C:\Users\USER\Downloads\Chat_With_Bot\BotServer\VkServiceApplication\Dockerfile


networks:
  my-network:
    #internal: true
    #driver: overlay