version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    volumes:
        - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
        - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
        #- 7888:7888
        - 5672:5672
        - 15672:15672
    
  serverapp:
    image: ${DOCKER_REGISTRY-}serverapp
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    depends_on:
        - rabbitmq
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile  
    depends_on:
     - rabbitmq


